#!/bin/sh
#
# @name OpenUAS Apprentice
#
# @type Standard Plane
# @class Plane
#


sh /etc/init.d/rc.fw_defaults

if [ $AUTOCNF = yes ]
then
	param set EKF2_ARSP_THR 8
	param set EKF2_FUSE_BETA 1
	param set EKF2_MAG_ACCLIM 0
	param set EKF2_MAG_YAWLIM 0

	#autonomous landing parameters
	param set FW_LND_USETER 1
	param set FW_LND_AIRSPD_SC 1
	param set FW_LND_ANG 3
	#param set FW_THR_LND_MAX 0.2

	param set FW_L1_PERIOD 12

	#wheel steering
	param set FW_W_EN 1

	#minimum loiter and takeoff alt.
	param set MIS_LTRMIN_ALT 30
	param set MIS_TAKEOFF_ALT 30
	#default loiter radius
	param set NAV_LOITER_RAD 50

	#waypoint acceptance radius
	param set NAV_ACC_RAD 15
	#datalink loss failsafe mode
	param set NAV_DLL_ACT 2

	#takeoff from runway
	param set RWTO_TKOFF 1

	#distance sensor for altimeter
	#Benewake TFmini RangeFinder, Telem 2 port
	#param set SENS_TFMINI_CFG 102

	#Lightware SF11/c rangefinder, Telem 2 port
	param set SENS_EN_SF0X 5
	param set SENS_SF0X_CFG 102

	#use range finder for altitude estimate
	param set EKF2_TERR_MASK 3
	param set EKF2_RNG_AID 1
	param set EKF2_RNG_A_VMAX 2
	param set EKF2_RNG_A_HMAX 10
	param set EKF2_MIN_RNG 0.06

	#enable "Full rate estimator (EKF2) replay topics" for logging
	param set SDLOG_PROFILE 3
fi

set MAV_TYPE 1
set MIXER open_uas_apprentice
